-- Follow-up to insulin-needles-tier-merge.sql: swaps the 10ct/$10.50 tier
-- for 30ct/$35, and gives each tier its own real product photo (a shared
-- placeholder photo, images/insulin-needles.png, was used for both before
-- this -- see insulin-needles-tier-merge.sql's own note that there was
-- never a second photo to choose between at the time).
--
-- New photos generated by scripts/generate-dosage-images.js? No -- these
-- are real product photography (box shots), not template composites, same
-- as the Peptide Carrier photo swap. Converted from the PNGs dropped in
-- the repo (images/insulin-needle-30ct.png, images/insulin-needle-100ct.png)
-- to WebP at quality 85 (images/insulin-needle-30ct.webp,
-- images/insulin-needle-100ct.webp), matching the site's existing image
-- convention -- image_path below still points at the .png name per
-- resolveImagePath()'s .png->.webp swap.
--
-- Confirmed both source photos actually show "31 GAUGE / 1mL CC / 5/16"
-- 8mm" on the box before using them -- matches the existing "31G, 5/16""
-- bullet line, unchanged by this migration.
--
-- IMPORTANT DEPLOY ORDER: apply this BEFORE the frontend git pull deploy.
-- The old shared image (images/insulin-needles.webp) is removed from the
-- repo in the same commit as this migration, so a git pull that lands
-- before this runs would leave insulin-needles-large-pack (still
-- pointing at the old path until this UPDATE runs) with a broken image.
--
-- Apply with:
--   psql -h localhost -U forgewell -d forgewell_db -f insulin-needles-30ct-photos-update.sql

BEGIN;

UPDATE products SET
  name = 'Insulin Needles (30ct)',
  dosage = '30ct',
  price = 35.00,
  image_path = 'images/insulin-needle-30ct.png'
WHERE id = 'insulin-needles-small-pack';

UPDATE products SET
  image_path = 'images/insulin-needle-100ct.png'
WHERE id = 'insulin-needles-large-pack';

COMMIT;

-- ============================================================
-- Verification query -- run after COMMIT to confirm:
--   SELECT id, name, dosage, price, image_path FROM products
--     WHERE id IN ('insulin-needles-small-pack', 'insulin-needles-large-pack');
--   -- should show "Insulin Needles (30ct)" at $35.00 with the 30ct image,
--   -- and "Insulin Needles (100ct)" at $95.00 (unchanged) with the 100ct image
-- ============================================================
