-- Generated from purity-99-handoff.csv (183 rows).
-- Sets purity=99 for every product below; also updates image_path where
-- the generated file uses a new filename (136 rows). 47 rows only touch
-- purity since their image_path already matched the newly generated file.
BEGIN;

UPDATE products SET purity = '99', image_path = 'images/bpc-157-kit-10mg-tpl.png' WHERE id = 'bpc-157-kit-10mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/bpc-157-kit-5mg-tpl.png' WHERE id = 'bpc-157-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/mots-c-10mg-tpl.png' WHERE id = 'mots-c-low';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-100mg-tpl.png' WHERE id = 'retatrutide-high';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-blend-kit-20mg-20mg-tpl.png' WHERE id = 'bpc-tb-blend-kit-20mg-20mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/pancragen-15mg-tpl.png' WHERE id = 'pancragen';
UPDATE products SET purity = '99', image_path = 'images/pt-141-kit-10mg-tpl.png' WHERE id = 'pt-141-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/semaglutide-kit-5mg-tpl.png' WHERE id = 'semaglutide-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/mots-c-kit-40mg-tpl.png' WHERE id = 'mots-c-kit-40mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/ss-31-kit-50mg-tpl.png' WHERE id = 'ss-31-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/sermorelin-kit-10mg-tpl.png' WHERE id = 'sermorelin-kit-10mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-kit-30mg-tpl.png' WHERE id = 'tirzepatide-kit-30mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ll-37-5mg-tpl.png' WHERE id = 'll-37';
UPDATE products SET purity = '99', image_path = 'images/sermorelin-kit-5mg-tpl.png' WHERE id = 'sermorelin-kit-5mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/semaglutide-kit-10mg-tpl.png' WHERE id = 'semaglutide-kit-10mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/dsip-15mg-tpl.png' WHERE id = 'dsip-high';
UPDATE products SET purity = '99', image_path = 'images/l-carnitine-600mg-tpl.png' WHERE id = 'l-carnitine-high';
UPDATE products SET purity = '99', image_path = 'images/pt-141-kit-10mg-tpl.png' WHERE id = 'pt-141-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-kit-10mg-tpl.png' WHERE id = 'tirzepatide-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/cagrilintide-10mg-tpl.png' WHERE id = 'cagrilintide';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-100mg-tpl.png' WHERE id = 'retatrutide-kit-100mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/mots-c-kit-40mg-tpl.png' WHERE id = 'mots-c-kit-40mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/tesamorelin-5mg-tpl.png' WHERE id = 'tesamorelin-low';
UPDATE products SET purity = '99', image_path = 'images/ipamorelin-10mg-tpl.png' WHERE id = 'ipamorelin-high';
UPDATE products SET purity = '99', image_path = 'images/5-amino-1mq-50mg-tpl.png' WHERE id = '5-amino-1mq';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-blend-kit-20mg-20mg-tpl.png' WHERE id = 'bpc-tb-blend-kit-20mg-20mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/mt-2-kit-10mg-tpl.png' WHERE id = 'mt-2-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-60mg-tpl.png' WHERE id = 'tirzepatide-high';
UPDATE products SET purity = '99', image_path = 'images/klow-80mg-tpl.png' WHERE id = 'klow';
UPDATE products SET purity = '99', image_path = 'images/tesamorelin-kit-5mg-tpl.png' WHERE id = 'tesamorelin-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/pnc-27-5mg-tpl.png' WHERE id = 'pnc-27';
UPDATE products SET purity = '99', image_path = 'images/tb-500-kit-10mg-tpl.png' WHERE id = 'tb-500-kit-10mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-kit-10mg-tpl.png' WHERE id = 'tirzepatide-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/kpv-kit-10mg-tpl.png' WHERE id = 'kpv-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ghk-cu-kit-50mg-tpl.png' WHERE id = 'ghk-cu-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-10mg-tpl.png' WHERE id = 'retatrutide-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/mt-2-kit-10mg-tpl.png' WHERE id = 'mt-2-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/mt-2-10mg-tpl.png' WHERE id = 'mt-2';
UPDATE products SET purity = '99', image_path = 'images/cagrilintide-kit-10mg-tpl.png' WHERE id = 'cagrilintide-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-500-mix-5mg-5mg-tpl.png' WHERE id = 'bpc-tb500-mix-low';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-blend-kit-5mg-5mg-tpl.png' WHERE id = 'bpc-tb-blend-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/survodutide-10mg-tpl.png' WHERE id = 'survodutide';
UPDATE products SET purity = '99', image_path = 'images/dsip-5mg-tpl.png' WHERE id = 'dsip-low';
UPDATE products SET purity = '99', image_path = 'images/cjc-1295-ipamorelin-10mg-10mg-tpl.png' WHERE id = 'cjc-1295-ipamorelin-high';
UPDATE products SET purity = '99', image_path = 'images/l-carnitine-200mg-tpl.png' WHERE id = 'l-carnitine-low';
UPDATE products SET purity = '99', image_path = 'images/testagen-20mg-tpl.png' WHERE id = 'testagen';
UPDATE products SET purity = '99', image_path = 'images/tesamorelin-kit-20mg-tpl.png' WHERE id = 'tesamorelin-kit-20mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/sermorelin-kit-5mg-tpl.png' WHERE id = 'sermorelin-kit';
UPDATE products SET purity = '99', image_path = 'images/tb-500-5mg-tpl.png' WHERE id = 'tb-500';
UPDATE products SET purity = '99', image_path = 'images/prostamax-10mg-tpl.png' WHERE id = 'prostamax';
UPDATE products SET purity = '99', image_path = 'images/mt-1-kit-10mg-tpl.png' WHERE id = 'mt-1-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/tb-500-kit-5mg-tpl.png' WHERE id = 'tb-500-kit-5mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-10mg-tpl.png' WHERE id = 'retatrutide-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-10mg-tpl.png' WHERE id = 'tirzepatide-low';
UPDATE products SET purity = '99', image_path = 'images/vesugen-20mg-tpl.png' WHERE id = 'vesugen';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-kit-20mg-tpl.png' WHERE id = 'tirzepatide-kit-20mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/chonluten-10mg-tpl.png' WHERE id = 'chonluten';
UPDATE products SET purity = '99', image_path = 'images/ghk-cu-50mg-tpl.png' WHERE id = 'ghk-cu-low';
UPDATE products SET purity = '99', image_path = 'images/cjc-ipa-blend-kit-5mg-5mg-tpl.png' WHERE id = 'cjc-ipa-blend-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/snap-8-10mg-tpl.png' WHERE id = 'snap-8';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-100mg-tpl.png' WHERE id = 'retatrutide-kit-100mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-500-mix-10mg-10mg-tpl.png' WHERE id = 'bpc-tb500-mix-10mg';
UPDATE products SET purity = '99', image_path = 'images/bpc-157-kit-10mg-tpl.png' WHERE id = 'bpc-157-kit-10mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/cortagen-10mg-tpl.png' WHERE id = 'cortagen';
UPDATE products SET purity = '99', image_path = 'images/ghk-cu-kit-100mg-tpl.png' WHERE id = 'ghk-cu-kit-100mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/adamax-10mg-tpl.png' WHERE id = 'adamax';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-30mg-tpl.png' WHERE id = 'retatrutide-kit-30mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/semax-selank-10mg-10mg-tpl.png' WHERE id = 'semax-selank-high';
UPDATE products SET purity = '99', image_path = 'images/kpv-kit-10mg-tpl.png' WHERE id = 'kpv-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/epithalon-10mg-tpl.png' WHERE id = 'epithalon';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-500-mix-20mg-20mg-tpl.png' WHERE id = 'bpc-tb500-mix-high';
UPDATE products SET purity = '99', image_path = 'images/sermorelin-5mg-tpl.png' WHERE id = 'sermorelin';
UPDATE products SET purity = '99', image_path = 'images/ghk-cu-kit-50mg-tpl.png' WHERE id = 'ghk-cu-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/mt-1-10mg-tpl.png' WHERE id = 'mt-1';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-kit-60mg-tpl.png' WHERE id = 'tirzepatide-kit-60mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ipamorelin-5mg-tpl.png' WHERE id = 'ipamorelin-low';
UPDATE products SET purity = '99', image_path = 'images/bpc-157-kit-5mg-tpl.png' WHERE id = 'bpc-157-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/cjc-ipa-blend-kit-10mg-10mg-tpl.png' WHERE id = 'cjc-ipa-blend-kit-10mg-10mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-blend-kit-10mg-10mg-tpl.png' WHERE id = 'bpc-tb-blend-kit-10mg-10mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ghrp-2-10mg-tpl.png' WHERE id = 'ghrp-2';
UPDATE products SET purity = '99', image_path = 'images/sermorelin-kit-10mg-tpl.png' WHERE id = 'sermorelin-kit-10mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-kit-60mg-tpl.png' WHERE id = 'tirzepatide-kit-60mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/glow-pro-blend-50mg-10mg-10mg-tpl.png' WHERE id = 'glow-pro-blend';
UPDATE products SET purity = '99', image_path = 'images/cartalax-20mg-tpl.png' WHERE id = 'cartalax';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-20mg-tpl.png' WHERE id = 'retatrutide-kit-20mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/livagen-20mg-tpl.png' WHERE id = 'livagen';
UPDATE products SET purity = '99', image_path = 'images/kpv-10mg-tpl.png' WHERE id = 'kpv-low';
UPDATE products SET purity = '99', image_path = 'images/semax-selank-5mg-5mg-tpl.png' WHERE id = 'semax-selank-low';
UPDATE products SET purity = '99', image_path = 'images/igf-1-lr3-kit-1mg-tpl.png' WHERE id = 'igf1-lr3-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ghk-cu-kit-200mg-tpl.png' WHERE id = 'ghk-cu-kit-200mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/cagrilintide-kit-10mg-tpl.png' WHERE id = 'cagrilintide-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ovagen-20mg-tpl.png' WHERE id = 'ovagen';
UPDATE products SET purity = '99', image_path = 'images/igf-1-lr3-kit-1mg-tpl.png' WHERE id = 'igf1-lr3-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/tb-500-kit-10mg-tpl.png' WHERE id = 'tb-500-kit-10mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ara-290-10mg-tpl.png' WHERE id = 'ara-290';
UPDATE products SET purity = '99', image_path = 'images/mots-c-40mg-tpl.png' WHERE id = 'mots-c-high';
UPDATE products SET purity = '99', image_path = 'images/ss-31-kit-50mg-tpl.png' WHERE id = 'ss-31-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/ghk-cu-kit-200mg-tpl.png' WHERE id = 'ghk-cu-kit-200mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/pinealon-20mg-tpl.png' WHERE id = 'pinealon';
UPDATE products SET purity = '99', image_path = 'images/cjc-ipa-blend-kit-5mg-5mg-tpl.png' WHERE id = 'cjc-ipa-blend-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/kisspeptin-10mg-tpl.png' WHERE id = 'kisspeptin';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-kit-20mg-tpl.png' WHERE id = 'tirzepatide-kit-20mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/tesamorelin-kit-20mg-tpl.png' WHERE id = 'tesamorelin-kit-20mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/tesamorelin-20mg-tpl.png' WHERE id = 'tesamorelin-high';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-blend-kit-5mg-5mg-tpl.png' WHERE id = 'bpc-tb-blend-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/tb-500-kit-5mg-tpl.png' WHERE id = 'tb-500-kit';
UPDATE products SET purity = '99', image_path = 'images/thymalin-10mg-tpl.png' WHERE id = 'thymalin';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-10mg-tpl.png' WHERE id = 'retatrutide-low';
UPDATE products SET purity = '99', image_path = 'images/mots-c-kit-10mg-tpl.png' WHERE id = 'mots-c-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/cjc-ipa-blend-kit-10mg-10mg-tpl.png' WHERE id = 'cjc-ipa-blend-kit-10mg-10mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ghk-cu-200mg-tpl.png' WHERE id = 'ghk-cu-high';
UPDATE products SET purity = '99', image_path = 'images/tesamorelin-kit-10mg-tpl.png' WHERE id = 'tesamorelin-kit-10mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/bronchogen-20mg-tpl.png' WHERE id = 'bronchogen';
UPDATE products SET purity = '99', image_path = 'images/pt-141-10mg-tpl.png' WHERE id = 'pt-141';
UPDATE products SET purity = '99', image_path = 'images/mt-1-kit-10mg-tpl.png' WHERE id = 'mt-1-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/tesamorelin-kit-10mg-tpl.png' WHERE id = 'tesamorelin-kit-10mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/vip-10mg-tpl.png' WHERE id = 'vip-high';
UPDATE products SET purity = '99', image_path = 'images/mots-c-kit-10mg-tpl.png' WHERE id = 'mots-c-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/crystagen-10mg-tpl.png' WHERE id = 'crystagen';
UPDATE products SET purity = '99', image_path = 'images/tesamorelin-kit-5mg-tpl.png' WHERE id = 'tesamorelin-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/bpc-tb-blend-kit-10mg-10mg-tpl.png' WHERE id = 'bpc-tb-blend-kit-10mg-10mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/klow-kit-80mg-tpl.png' WHERE id = 'klow-kit-5-pack';
UPDATE products SET purity = '99', image_path = 'images/cjc-1295-ipamorelin-5mg-5mg-tpl.png' WHERE id = 'cjc-1295-ipamorelin-low';
UPDATE products SET purity = '99', image_path = 'images/tirzepatide-kit-30mg-tpl.png' WHERE id = 'tirzepatide-kit-30mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-20mg-tpl.png' WHERE id = 'retatrutide-kit-20mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-50mg-tpl.png' WHERE id = 'retatrutide-kit-50mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/vip-5mg-tpl.png' WHERE id = 'vip-low';
UPDATE products SET purity = '99', image_path = 'images/klow-kit-80mg-tpl.png' WHERE id = 'klow-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/ghrp-6-10mg-tpl.png' WHERE id = 'ghrp-6';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-50mg-tpl.png' WHERE id = 'retatrutide-kit-50mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/retatrutide-kit-30mg-tpl.png' WHERE id = 'retatrutide-kit-30mg-5-pack';
UPDATE products SET purity = '99', image_path = 'images/igf1-lr3-1mg-tpl.png' WHERE id = 'igf1-lr3';
UPDATE products SET purity = '99', image_path = 'images/ghk-cu-kit-100mg-tpl.png' WHERE id = 'ghk-cu-kit-100mg-10-pack';
UPDATE products SET purity = '99', image_path = 'images/hexarelin-5mg-tpl.png' WHERE id = 'hexarelin';
UPDATE products SET purity = '99', image_path = 'images/semaglutide-kit-5mg-tpl.png' WHERE id = 'semaglutide-kit-10-pack';
UPDATE products SET purity = '99', image_path = 'images/semaglutide-kit-10mg-tpl.png' WHERE id = 'semaglutide-kit-10mg-5-pack';
UPDATE products SET purity = '99' WHERE id = 'tirzepatide-30mg';
UPDATE products SET purity = '99' WHERE id = 'morning-relax';
UPDATE products SET purity = '99' WHERE id = 'glutathione';
UPDATE products SET purity = '99' WHERE id = 'body-boost';
UPDATE products SET purity = '99' WHERE id = 'l-carnitine-400mg';
UPDATE products SET purity = '99' WHERE id = 'tesamorelin-10mg';
UPDATE products SET purity = '99' WHERE id = 'dsip-10mg';
UPDATE products SET purity = '99' WHERE id = 'ss-31-50mg';
UPDATE products SET purity = '99' WHERE id = 'tb-500-10mg';
UPDATE products SET purity = '99' WHERE id = 'power-blitz';
UPDATE products SET purity = '99' WHERE id = 'neuro-spark';
UPDATE products SET purity = '99' WHERE id = 'acetyl-d-glucosamine';
UPDATE products SET purity = '99' WHERE id = 'tirzepatide-20mg';
UPDATE products SET purity = '99' WHERE id = 'tri-immune-blend';
UPDATE products SET purity = '99' WHERE id = 'metabolic-fire';
UPDATE products SET purity = '99' WHERE id = 'yohimbine-hcl';
UPDATE products SET purity = '99' WHERE id = 'semaglutide-10mg';
UPDATE products SET purity = '99' WHERE id = 'hair-skin-nails-blend';
UPDATE products SET purity = '99' WHERE id = 'pump-xxl';
UPDATE products SET purity = '99' WHERE id = 'peak-performance';
UPDATE products SET purity = '99' WHERE id = 'power-burn';
UPDATE products SET purity = '99' WHERE id = 'sleep-mix';
UPDATE products SET purity = '99' WHERE id = 'sermorelin-10mg';
UPDATE products SET purity = '99' WHERE id = 'vitality-vibe';
UPDATE products SET purity = '99' WHERE id = 'ghk-cu-100mg';
UPDATE products SET purity = '99' WHERE id = 'cjc-1295';
UPDATE products SET purity = '99' WHERE id = 'bpc-157-5mg';
UPDATE products SET purity = '99' WHERE id = 'selank';
UPDATE products SET purity = '99' WHERE id = 'b6';
UPDATE products SET purity = '99' WHERE id = 'bcaa-211';
UPDATE products SET purity = '99' WHERE id = 'pump-xl';
UPDATE products SET purity = '99' WHERE id = 'nac';
UPDATE products SET purity = '99' WHERE id = 'semaglutide-5mg';
UPDATE products SET purity = '99' WHERE id = 'vitamin-c';
UPDATE products SET purity = '99' WHERE id = 'helios-extreme';
UPDATE products SET purity = '99' WHERE id = 'retatrutide-30mg';
UPDATE products SET purity = '99' WHERE id = 'hmg';
UPDATE products SET purity = '99' WHERE id = 'energy-lipo-blend';
UPDATE products SET purity = '99' WHERE id = 'ss-31-10mg';
UPDATE products SET purity = '99' WHERE id = 'nad-plus';
UPDATE products SET purity = '99' WHERE id = 'retatrutide-50mg';
UPDATE products SET purity = '99' WHERE id = 'retatrutide-20mg';
UPDATE products SET purity = '99' WHERE id = 'vilon-10mg';
UPDATE products SET purity = '99' WHERE id = 'mic-blend';
UPDATE products SET purity = '99' WHERE id = 'recovery-rush';
UPDATE products SET purity = '99' WHERE id = 'b12';
UPDATE products SET purity = '99' WHERE id = 'semax';

COMMIT;
